### ISSUE TITLE
API Key Instructions in the README?

### ISSUE THREAD

**Issue by carljv** [WarbyParker/cbsafinder#1]
To use this, I think you need to have both a CENSUS_API_KEY and GOOGLE_API_KEY in your environment.

Did you want to add instructions for getting those keys and adding them to .Renviron?

**Comment by sursh** [comment]
There's instructions for the google api key in a vignette—good idea linking to it from the README

**Comment by robinsones** [comment]
Added instructions on viewing vignette to ReadMe in 3806d86cb38ec9d6f40917d217e44ef059a8d4b0
