### ISSUE TITLE
Error due to ACS2015_Current vintage geographies are no longer being available

### ISSUE THREAD

**Issue by carljv** [WarbyParker/cbsafinder#3]
Calls to geocode_address will error out with a Bad Address error. This is being caused by the call to the Census geocoding API. That function currently passes "ACS2015_Current" as the vintage parameter. That geography vintage is apparently no longer available under the Public_AR_Current, or any other benchmark. 

Given the audience for the package, Current_Current is probably a better setting for the vintage, and is basically guaranteed not to expire.

I've fixed this in PR #2 .

**Comment by robinsones** [comment]
Merged PR, thanks Carl!
